name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install mdbook
        uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdBook
          version: "0.4.21"
      - name: Clean output folder
        run: mdbook clean
      - name: Build book
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
          force_orphan: false
